### ISSUE TITLE
O script esta dando erro para mim

### ISSUE THREAD

**Issue by Mateus5520** [likizao/vrp_onservice#1]
quando aperto "E" no jogo o script da erro na base, o que poderia ser?
![Sem título](https://user-images.githubusercontent.com/51725183/60213135-35855880-9839-11e9-819e-edefaeb2e902.png)

**Comment by likizao** [comment]
Tá usando a base do B2K? Se não estiver, certifique-se de trocar `    table.insert(fields, { name = "Nome e Sobrenome:", value = ''..identity.nome..' '..identity.sobrenome, inline = true }); ` para `table.insert(fields, { name = "Nome e Sobrenome:", value = ''..identity.name..' '..identity.firstname, inline = true }); 
`
E na linha 48 altere para  `content = ''..identity.name..' '..identity.firstname.' '..acao,` Se der erro novamente. mande print do console inteiro.

**Comment by Mateus5520** [comment]
eu já havia feito essas mudanças, esse erro foi já com as mudanças feitas, a base não é a do B2K

**Comment by likizao** [comment]
Antes da mudança, o erro era o mesmo?

**Comment by Mateus5520** [comment]
era sim, ai fiz a mudança e atualizei o artifacts para ver se resolvia e n resolveu

**Comment by Mateus5520** [comment]
acho q é incompatibilidade com a minha base

**Comment by likizao** [comment]
Não faz sentido, me procura no discord. Likizão#1479
